#!/bin/sh

set -e
cd `dirname $0`

name=`basename $PWD`

deactivate 2> /dev/null || true
test -d venv && rm -rf venv
virtualenv venv --prompt "(${name}) "
. ./venv/bin/activate
pip install -r requirements.txt

ln -sf ../../pre-commit .git/hooks/pre-commit
